name: third_party_login
description: Third Party Login is simple way to sign-in with different types of third party login systems.
version: 1.0.14
homepage: https://github.com/knatnaela/third_party_login

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.15.3
  flutter_facebook_auth: ^6.0.3
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter.
flutter:
# The example deliberately includes limited-use secrets.
false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/ios/RunnerTests/GoogleSignInTests.m
  - /example/lib/main.dart
  - /example/web/index.html
