name: third_party_login
description: Third Party Login is simple way to sign-in with different types of third party login systems.
version: 1.0.0
homepage: https://github.com/knatnaela/third_party_login

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  font_awesome_flutter: ^9.2.0

  google_sign_in: ^5.2.1
  firebase_auth: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
# The example deliberately includes limited-use secrets.
false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
  - /example/ios/RunnerTests/GoogleSignInTests.m
  - /example/lib/main.dart
  - /example/web/index.html
